# Generated by Django 5.2.6 on 2025-11-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=50)),
                ('room_num', models.IntegerField(default=0)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('office_hr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(default='00000000', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('is_mvp', models.BooleanField(default=True)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('course_subject', models.CharField(choices=[('Chinese', 'Chinese'), ('English', 'English'), ('Math', 'Math'), ('liberal Studies', 'Liberal Studies'), ('Economics', 'Economics'), ('History', 'History'), ('Geography', 'Geography'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], default='Chinese', help_text='Subject taught by the tutor', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating from 0.0 to 5.0', max_digits=2)),
                ('experience', models.CharField(default=1, help_text='Years of experience', max_length=20)),
                ('taught_students', models.PositiveIntegerField(default=100, help_text='Number of students taught')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the course', max_length=200)),
                ('district', models.CharField(choices=[('Islands', 'Islands'), ('Kwai Tsing', 'Kwai Tsing'), ('North', 'North'), ('Sai Kung', 'Sai Kung'), ('Sha Tin', 'Sha Tin'), ('Tai Po', 'Tai Po'), ('Tsuen Wan', 'Tsuen Wan'), ('Tuen Mun', 'Tuen Mun'), ('Yuen Long', 'Yuen Long'), ('Kowloon City', 'Kowloon City'), ('Kwun Tong', 'Kwun Tong'), ('Sham Shui Po', 'Sham Shui Po'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Central & Western', 'Central & Western'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Wan Chai', 'Wan Chai')], default='Sha Tin', help_text='District where the course is offered', max_length=50)),
                ('subject', models.CharField(choices=[('Chinese', 'Chinese'), ('English', 'English'), ('Math', 'Math'), ('liberal Studies', 'Liberal Studies'), ('Economics', 'Economics'), ('History', 'History'), ('Geography', 'Geography'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], default='Chinese', help_text='Subject matter of the course', max_length=50)),
                ('students_enrolled', models.PositiveIntegerField(default=0, help_text='Current number of students enrolled')),
                ('max_students', models.PositiveIntegerField(default=20, help_text='Maximum number of students allowed')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating from 0.0 to 5.0', max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, help_text='Course price in HKD', max_digits=8)),
                ('duration', models.PositiveIntegerField(default=1.5, help_text='Course duration in hours')),
                ('total_classes', models.PositiveIntegerField(default=4, help_text='Total number of classes in the course')),
                ('class_time', models.CharField(default='Wed 4 p.m.', help_text='Scheduled time for the class (e.g., Wed 4 p.m.)', max_length=50)),
                ('class_type', models.CharField(choices=[('live', 'Live'), ('video', 'Video')], default='live', help_text='Delivery format of the course', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the course', null=True)),
                ('school', models.ForeignKey(blank=True, help_text='School offering the course', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='education.school')),
                ('tutor', models.ForeignKey(help_text='Tutor teaching this course', on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='education.tutor')),
            ],
        ),
    ]
