# Generated by Django 5.2.6 on 2025-11-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Course duration in hours'),
        ),
    ]
